// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFPG68QFV-mCqkb6_1nhjkkDCgMkhvHpM',
    appId: '1:1062615547138:web:e29ca2932720bcf49ad61b',
    messagingSenderId: '1062615547138',
    projectId: 'littup-fe8b2',
    authDomain: 'littup-fe8b2.firebaseapp.com',
    storageBucket: 'littup-fe8b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwHHBK8l7xdn-ItJSYh3qNqHm8tIngLcA',
    appId: '1:1062615547138:android:3cb65886dff781329ad61b',
    messagingSenderId: '1062615547138',
    projectId: 'littup-fe8b2',
    storageBucket: 'littup-fe8b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0C_eMPGh7KmbY21Nhst0bf6u1HqYy840',
    appId: '1:1062615547138:ios:eff83729eeafef0b9ad61b',
    messagingSenderId: '1062615547138',
    projectId: 'littup-fe8b2',
    storageBucket: 'littup-fe8b2.firebasestorage.app',
    iosBundleId: 'com.example.littup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0C_eMPGh7KmbY21Nhst0bf6u1HqYy840',
    appId: '1:1062615547138:ios:eff83729eeafef0b9ad61b',
    messagingSenderId: '1062615547138',
    projectId: 'littup-fe8b2',
    storageBucket: 'littup-fe8b2.firebasestorage.app',
    iosBundleId: 'com.example.littup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFPG68QFV-mCqkb6_1nhjkkDCgMkhvHpM',
    appId: '1:1062615547138:web:2adad9472dd3ccef9ad61b',
    messagingSenderId: '1062615547138',
    projectId: 'littup-fe8b2',
    authDomain: 'littup-fe8b2.firebaseapp.com',
    storageBucket: 'littup-fe8b2.firebasestorage.app',
  );
}
